steps:

# We don't need the git checkout step, since it's already part of the git commit trigger

- name: 'gcr.io/cloud-builders/git'
  id: 'git-checkout'
  args: ['clone', 'https://github.com/mablhq/calculator.git', 'calc']
  dir: 'build'

# TODO push a prebuild npm image with these modules preinstalled for faster startup
- name: 'gcr.io/cloud-builders/npm'
  id: 'npm-install'
  args: ['install']
  dir: 'build/calc'

- name: 'gcr.io/cloud-builders/npm'
  id: 'build-webapp'
  args: ['run-script', 'build']
  dir: 'build/calc'

# TODO add dynamic fragment so we can unique url and cache busting
# TODO make webpack stop moving js/css into static path - prevents above dynamic fragment
- name: gcr.io/cloud-builders/gsutil
  id: 'deploy-to-gcs'
  args: ['-m', 'rsync', '-r', '-a', 'public-read', 'build/', 'gs://mabl-demo-static-test-assets/calc/v4/' ]
  dir: 'build/calc'

# Have mabl run the smoke tests
- name: 'gcr.io/cloud-builders/curl'
  id: 'trigger-smoke-tests'
  entrypoint: 'bash'
  args: ['-c','curl -v 2 https://api-dev.mabl.com/events/deployment -u "key:$$MABL_API_KEY" -H "Content-Type:application/json" -d "{\"environment_id\":\"4Cbk2cPeqGIh8ym-33lSzw-e\",\"application_id\":\"wTmDPcGV6sy32fJxbB4UzA-a\"}"']
  secretEnv: ['MABL_API_KEY']

# Store our secret keys in KMS
secrets:
- kmsKeyName: projects/mabl-demo/locations/global/keyRings/cloud-builder-ring/cryptoKeys/cloud-builder-deploy-demo
  secretEnv:
    MABL_API_KEY: CiQAlIKSJlF7b9cVG9mDD54qjvXABtOGQnlYy7OJkJOMKspMF0oSPwA5zmC1J/45H3z/Oq7Qpyr6A+DlNRd7hQTyMtyhBI1pc7Ul+1W5ebUdO/WFeGomz199z2FJm5grxjPzzJp9Ig== 
