steps:

# TODO push a prebuild npm image with these modules preinstalled for faster startup
- name: 'gcr.io/cloud-builders/npm'
  id: 'npm-install'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  id: 'build-webapp'
  args: ['run-script', 'build']

# TODO add dynamic fragment so we can unique url and cache busting
# TODO make webpack stop moving js/css into static path - prevents above dynamic fragment
- name: gcr.io/cloud-builders/gsutil
  id: 'deploy-webapp-to-gcs'
  args: ['-m', 'rsync', '-r', '-a', 'public-read', 'build/', 'gs://mabl-demo-static-test-assets/calc/v4/' ]
    
# Have mabl run the smoke tests
- name: 'gcr.io/cloud-builders/curl'
  id: 'trigger-mabl-smoke-tests'
  entrypoint: 'bash'
  args: ['-c','curl -s https://api-dev.mabl.com/events/deployment -u "key:$$MABL_API_KEY" -H "Content-Type:application/json" -d "{\"environment_id\":\"4Cbk2cPeqGIh8ym-33lSzw-e\",\"application_id\":\"wTmDPcGV6sy32fJxbB4UzA-a\",\"plan_overrides\":{\"uri\":\"http://storage.googleapis.com/mabl-demo-static-test-assets/calc/v4/index.html\"}}"']
  secretEnv: ['MABL_API_KEY']

# Store our secret keys in KMS
secrets:
- kmsKeyName: projects/mabl-demo/locations/global/keyRings/cloud-builder-ring/cryptoKeys/cloud-builder-deploy-demo
  secretEnv:
    MABL_API_KEY: CiQAlIKSJlF7b9cVG9mDD54qjvXABtOGQnlYy7OJkJOMKspMF0oSPwA5zmC1J/45H3z/Oq7Qpyr6A+DlNRd7hQTyMtyhBI1pc7Ul+1W5ebUdO/WFeGomz199z2FJm5grxjPzzJp9Ig== 
